import { ContextProvider } from "./Context/Context";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import HeaaderPage from "./HeaderBar/TopHeader";

import Providers from "./provider";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ContextProvider>
            <div className="w-full h-svh m-auto overflow-hidden">
              <HeaaderPage />
              <div className="flex w-full h-[calc(100vh-40px)]">
                <aside id="side-nav"></aside>
                {children}
              </div>
            </div>
          </ContextProvider>
        </Providers>
        {/* <div className="w-full h-full bg-red-300">{children} </div> */}
      </body>
    </html>
  );
}
