import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import HeaaderPage from "./HeaderBar/TopHeader";
import SideBarPage from "./SideBarMenu/SideNavBar";

import Providers from "./provider";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="w-full h-svh m-auto overflow-hidden">
            <HeaaderPage />
            <div className="flex w-full h-[calc(100vh-40px)]">
              <SideBarPage />
              {children}
            </div>
          </div>
        </Providers>
        {/* <div className="w-full h-full bg-red-300">{children} </div> */}
      </body>
    </html>
  );
}
